### ISSUE TITLE
Get episodes info

### ISSUE THREAD

**Issue by Godoy** [Godoy/node-imdb-crawler#3]
A method that receives the Imdb Code and gets the following episode infos:
- Name
- Season
- Number (in season)
- Air date and time
- Summary
- Episode image (if exists)
 
Something like the following would be interesting:
```
imdb_crawler.get_basic(function(data) {
  console.log("Serie:");
  console.log(data);

  imdb_crawler.get_episodes(data.imdb_id, function(epi_data) {
    //epi_data
  });
})
```

**Comment by erickzhao** [comment]
I'd be interested in contributing for this. I'll try to whip up something within the next 24 hours? 😀
